version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: favorite_products_db_dev
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--appendfsync", "everysec",
      "--save", "",
      "--maxmemory-policy", "noeviction",
      "--io-threads", "4",
      "--io-threads-do-reads", "yes",
      "--loglevel", "warning",
      "--timeout", "300",
      "--tcp-backlog", "1024"
    ]
  haproxy:
    image: haproxy:3.1.8-alpine3.22
    container_name: haproxy-load-balancer-dev
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "9999:9999"